using System;

    class Program
    {
        static void Main(string[] args)
        {
           /*Euler 1. If we list the natural number below 10 that are multiplies of 3 or 5,
           we get 3,5,6,9. The sum of these multiples is 23. 
           Find the sum of all the multiples of 3 or 5 below 1000.*/
           
           /*int sum = 0, 
           sum2 = 0,
           sum3 = 0;


           //All the numbers that can be divided by 3 but not 5
            for (int i = 1; i <= 1000; i++)
            {
                if ( i % 3 == 0 && i % 5 != 0)
                {
                    sum += i;
                }
                
            }

           // Console.WriteLine(sum);

           //All number that can be divided by 5 but not 3
           for (int i = 1; i <= 100; i++)
           {
               if (i % 5 == 0 && i % 3 != 0)
               {
                   sum2 += i;
               }
           }
           //Console.WriteLine(sum2);


           // All numbers that can be divided by 5 and 3

           for (int i = 1; i <= 100; i++)
           {
               if (i % 5 == 0 && i % 3 == 0)
               {
                   sum3 += i;
               }
           }
           //Console.WriteLine(sum3);

           //Sum of these
           Console.WriteLine(sum + sum2 + sum3);
           */

           /* Euler 2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
           By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
           By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
           find the sum of the even-valued terms.*/
           

           int a = 0, b = 1, c = 0, fibon = 0;
           while ( c <= 4000000)
           {
               c = a + b;
               if (c % 2 == 0)
               {
                   Console.Write("{0} ", c);
               }

               a = b;
               b = c;

               if (c % 2 == 0)
                {
               fibon += c;
                }

               if (c >= 4000000)
               {
                   break;
               }
           }

           Console.Write(fibon);
    



        }
    }

